"""empty message

Revision ID: 085d70b3cb77
Revises: a5cffa318ac2
Create Date: 2025-08-18 14:53:33.182072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '085d70b3cb77'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(), nullable=False, foreign_key=True),
    sa.Column('text', sa.String(length=120), nullable=True),
    sa.Column('like', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(), nullable=False, foreign_key=True),
    sa.Column('date', sa.String(length=8), nullable=False),
    sa.Column('caption', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(), nullable=False, foreign_key=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('story')
    op.drop_table('post')
    op.drop_table('coment')
    # ### end Alembic commands ###
